//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKursovayaEntities : DbContext
    {
        private static DBKursovayaEntities _context;

        public static DBKursovayaEntities GetContext()
        {
            if (_context == null)
                _context = new DBKursovayaEntities();
            return _context;
        }

        public DBKursovayaEntities()
            : base("name=DBKursovayaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Jeweler> Jeweler { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Order_> Order_ { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Types_> Types_ { get; set; }
    }
}
