//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeweler
    {
        public Jeweler()
        {
            this.Order_ = new HashSet<Order_>();
        }
    
        public int JewelerID { get; set; }
        public string JewelerName { get; set; }
        public string JewelerPhone { get; set; }
        public Nullable<int> ItemID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ICollection<Order_> Order_ { get; set; }
    }
}
