//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> PrisePerGramm { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
