//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types_
    {
        public Types_()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
